package it.polimi.ingsw.Network.Message;

public enum MessageType {

/* ** FIRST FASE Message ** */
    CONNECT,
    LOGIN,
    REQUESTNUMPLAYERS, //??
    WAITINGOTHERPLAYERS,  //?
    NUMPLAYERS,

/* ** INIT FASE Message ** */
    STARTGAME,
    CHOOSERESOURCESFIRSTTURN,
    CHOOSELEADERCARDS,


/* ** INGAME FASE Message ** */
    UPDATESTATELEADERCARDS,

    EXTRACTIONMARBLES,
    EXCHANGEWAREHOUSE,
    MANAGEMARBLES,

    ACTIVESBASEPRODUCTION,
    ACTIVEPRODUCTIONDEVCARD,
    ACTIVELEADERCARDPRODUCTION,
    ENDPRODUCTION,

    BUYDEVCARD,
    PAYRESOURCES,

    ENDTURN,


 /* ** update Message ** */
    UPDATECURRENTPLAYER,
    UPDATEPLAYERSTATE,

    UPDATERESOURCES,
    UPDATEMARKETTRAY,
    UPDATEDEVCARDDECK,

    UPDATEFAITHPOINTS,

    UPDATESTRONGBOX,
    UPDATEWAREHOUSE,
    UPDATESLOTDEVCARDS,

    UPDATESINGLEPLAYER,

    UPDATEWINNERMULTIPLAYER,
    UPDATEWINNERSINGLEPLAYER,

/* ** UTILITY Message ** */
    FINISHEDGAME,
    ENDGAME,
    SHOWMESSAGE,
    PING,
    DISCONNECT,
    ERROR;

}
