package it.polimi.ingsw.Network.message;

public enum MessageType {
    LOGIN,
    NUMPLAYERS,
    EXTRACTIONMARBLES,
    ADDDISCARDMARBLES,
    EXCHANGEWAREHOUSE,
    SELECTTRANSFORMATIONWHITEMARBLE,
    CHOOSELEADERCARDS,
    CHOOSERESOURCESFIRSTTURN,
    CHOOSERESOURCESDEVCARDPRODUCTION,
    CHOOSERESOURCESPURCHASEDEVCARD,
    INSERTCARD,
    SELECTDEVCARD,
    ACTIVESBASEPRODUCTION,
    CHOSENRESOURCEBASEPRODUCTION,
    ACTIVEPRODUCTIONDEVCARD,
    ACTIVELEADERCARDPRODUCTION,
    UPDATESTATELEADERACTION,
    ENDTURN,
    PING,
    DISCONNECT,
    EXTRACTEDMARBLESLIST,
    CHECKOK,
    REQUESTNUMPLAYERS,
    WAITINGOTHERPLAYERS,
    INITIALSITUATIONGAME,
    DELETEDEVCARD,
    ENDPRODUCTION,


    UPDATEMARKETTRAY,
    UPDATEFAITHPOINTS,
    UPDATESTRONGBOX,
    UPDATECURRENTPLAYER,
    UPDATEWAREHOUSE,
    UPDATESLOTDEVCARDS,
    UPDATEPLAYERLIST,
    UPDATERESOURCES,
    UPDATESTATELEADERCARDS,
    UPDATEFINALPOINTS,
    UPDATEWINNER,
    UPDATESINGLEPLAYER,
    CONNECT,


    CHOOSETURN,
    CHOOSEAFTERTAKEMARBLE,
    CHOOSEPRODUCTIONTYPE,
    ENDTURNACTIVELEADERCARD,

    UPDATEWINNERSINGLEPLAYER,
    UPDATEDEVCARDDECK,
    UPDATEWHITEMARBLEEFFECT,


    ENDGAME;
}
