package it.polimi.ingsw.Network.message;

public enum MessageType {
    NUMPLAYERS,
    EXTRACTIONMARBLES,
    ADDDISCARDMARBLES,
    EXCHANGEWAREHOUSE,
    CHOOSELEADERCARDS,
    CHOOSERESOURCES,
    INSERTCARD,
    SELECTDEVCARD,
}
