package it.polimi.ingsw.Network.message;

public enum MessageType {
    LOGIN,
    NUMPLAYERS,
    EXTRACTIONMARBLES,
    ADDDISCARDMARBLES,
    EXCHANGEWAREHOUSE,
    CHOOSELEADERCARDS,
    CHOOSERESOURCESFIRSTTURN,
    CHOOSERESOURCESFORPRODUCTION,
    CHOOSERESOURCESDEVCARD,
    INSERTCARD,
    SELECTDEVCARD,
    ACTIVEPRODUCTION,
    UPDATESTATELEADERACTION
}
